### ISSUE TITLE
Command-line execution

### ISSUE THREAD

**Issue by alercah** [F43nd1r/F43dit#1]
Is there a way to run this basically as a compiler from the command-line?

**Comment by F43nd1r** [comment]
Currently not. Shouldn't be too hard to build though.

**Comment by alercah** [comment]
I would greatly appreciate that, as configuring my editor to run-on-save so that I can F10 in game to load the solution would be the ideal workflow.

**Comment by F43nd1r** [comment]
Sorry, I was not saying I will program it. Just if someone decides to, it wouldn't be hard. I don't have the time right now.

**Comment by F43nd1r** [comment]
https://github.com/F43nd1r/F43dit/releases/tag/v1.2.3
